# Generated by Django 4.1.6 on 2023-02-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=2222)),
                ('model', models.CharField(max_length=222)),
                ('type', models.CharField(max_length=2222)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2222)),
                ('color', models.CharField(max_length=22)),
                ('type', models.CharField(max_length=22)),
                ('price', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.product')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('speed', models.SmallIntegerField()),
                ('ram', models.SmallIntegerField()),
                ('hd', models.IntegerField()),
                ('cd', models.CharField(max_length=2222)),
                ('price', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.product')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('speed', models.SmallIntegerField()),
                ('ram', models.SmallIntegerField()),
                ('hd', models.IntegerField()),
                ('cd', models.CharField(max_length=2222)),
                ('price', models.IntegerField()),
                ('screen', models.SmallIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.product')),
            ],
        ),
    ]
