# Generated by Django 4.1.5 on 2023-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='image',
            field=models.ImageField(default=1, upload_to='image/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
