# Generated by Django 4.1.5 on 2023-02-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
